name: Docker Image CI

on:
  push:
    branches: [ "main" ]
      # pull_request:
      #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the repository 
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-test-build:test
    
    - name: Run container
      run: docker run --name myContainer docker-test-build:test
        #deploy: 
        #runs-on: ubuntu-latest
        #steps:
        #- uses: actions/checkout@v4
        #- name: Deploy container
        #run: docker run --name myContainer docker-test-build:test
